spring.application.name=Gestion_Restaurant
spring.data.mongodb.uri=mongodb://localhost:27017/gestion_restaurant
server.port=8083
# Taille max d'un fichier
spring.servlet.multipart.max-file-size=10MB
# Taille max totale de la requete
spring.servlet.multipart.max-request-size=10MB